cluster_name: rke2-mdx1
cluster_domain: ip-163-220-178-192.compute.mdx1.jp

# FQDN（DNS で 80/443 を ingress ノードに向ける）
rancher_fqdn: rancher.ip-163-220-178-192.compute.mdx1.jp
harbor_fqdn: harbor.ip-163-220-178-192.compute.mdx1.jp
grafana_fqdn: grafana.ip-163-220-178-192.compute.mdx1.jp
prometheus_fqdn: prometheus.ip-163-220-178-192.compute.mdx1.jp
alert_fqdn: alert.ip-163-220-178-192.compute.mdx1.jp

# Let’s Encrypt
le_email: admin@ip-163-220-178-192.compute.mdx1.jp

# RKE2
rke2_channel: "stable"
rke2_server_ip: "{{ hostvars['mnode']['node_ip'] }}"
rke2_token: "{{ vault_rke2_token }}"

# Helm
helm_version: "v3.15.3"

# Cilium
enableHostPort: true
hostServices_enabled: true
routingMode: tunnel
kubeProxyReplacement: false

# Ingress
ingress_class: nginx
use_hostport: true

# Rancher 初期パスワード（初回ログイン後に変更）
rancher_bootstrap_password: "{{ vault_rancher_bootstrap }}"

# harbor
harbor_reset_pvcs: true
registry_external: "harbor.ip-163-220-178-192.compute.mdx1.jp:30543" 
registry_internal_http_endpoint: "http://10.43.73.29:5000"
registry_username: "robot$rancher"
registry_password: "4WMJYgffQlGkfU2tDlQwBSyjxlLyNMoL"
image_pull_namespaces: ["sprint-1", "sprint-2", "sprint-3"]
rke2_registries_path: "/etc/rancher/rke2/registries.yaml"

# Kubeconfig（playbook/ から見て 1 つ上）
kubeconfig_path: "{{ playbook_dir | dirname }}/.kube/rke2.yaml"

# NTP/Chrony サーバー
time_servers:
  - ntp.nict.jp
  - ntp.jst.mfeed.ad.jp
  - pool.ntp.org
