---
- hosts: bastion
  gather_facts: false
  vars:
    kubeconfig_path: "{{ playbook_dir | dirname }}/.kube/rke2.yaml"
    api_endpoint: "https://10.14.23.161:6443"
  tasks:
    - name: Ensure kubeconfig exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kube

    - name: Fail if kubeconfig is missing
      fail:
        msg: "kubeconfig not found at {{ kubeconfig_path }}. Run 10_rke2_server.yml first."
      when: not kube.stat.exists

    - name: Rewrite kubeconfig server endpoint to master IP
      replace:
        path: "{{ kubeconfig_path }}"
        regexp: '^(\s*server:\s*)https?://[^:]+:6443\s*$'
        replace: '\1{{ api_endpoint }}'
        backup: yes

