---
- name: Setup RKE2 server on master nodes
  hosts: masters
  become: true
  vars_files:
    - ../group_vars/all.yml

  vars:
    rke2_services:
      - rke2-server

  roles:
    - { role: rke2_server, tags: ["rke2", "server"] }

