---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/values.yml

  vars:
    kubeconfig_path: "{{ playbook_dir | dirname }}/.kube/rke2.yaml"
    cilium_values_file: "{{ playbook_dir | dirname }}/roles/cilium/files/values-cilium.yaml" 
  tasks:
    - name: Add cilium repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: Install/upgrade cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "1.16.3"        
        release_namespace: kube-system
        create_namespace: false
        kubeconfig: "{{ kubeconfig_path }}"
        reset_values: true
        atomic: true
        values_files:
          - "{{ cilium_values_file }}"

    - name: Render cilium-config override
      ansible.builtin.template:
        src: "{{ playbook_dir | dirname }}/roles/cilium/templates/cilium-config.override.yaml.j2"
        dest: "/tmp/cilium-config.override.yaml"

    - name: Apply cilium-config (force override)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        force: true
        src: "/tmp/cilium-config.override.yaml"

    - name: Restart cilium to reload config
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: patched
        definition:
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: cilium
            namespace: kube-system
          spec:
            template:
              metadata:
                annotations:
                  reload-at: "{{ lookup('ansible.builtin.pipe','date +%s') }}"
