---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  vars:
    kubeconfig_path: "{{ playbook_dir | dirname }}/.kube/rke2.yaml"

  tasks:
    - name: Apply Cilium role
      ansible.builtin.include_role:
        name: cilium

