---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  roles:
    - { role: kube_labels, tags: ["labels","ingress"] }
    - { role: ingress_nginx, tags: ["ingress"] }
