---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml

  vars:
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') | default(playbook_dir | dirname ~ '/.kube/rke2.yaml', true) }}"

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  roles:
    - { role: storage_localpath, tags: ["storageclass", "localpath"] }

