---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml

  pre_tasks:
    - name: Ensure kubeconfig exists
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kc
    - name: Fail if kubeconfig missing
      ansible.builtin.fail:
        msg: "kubeconfig not found: {{ kubeconfig_path }}"
      when: not kc.stat.exists
    - name: Pin kubeconfig server to RKE2 API ({{ rke2_server_ip }}:6443)
      ansible.builtin.replace:
        path: "{{ kubeconfig_path }}"
        regexp: '^(\\s*server:\\s*)https?://[^:]+(:[0-9]+)?'
        replace: '\1https://{{ rke2_server_ip }}:6443'
    - name: Show kubeconfig server
      ansible.builtin.shell: "awk '/server: /{print $2}' {{ kubeconfig_path }} | head -1"
      register: kc_server
      changed_when: false
    - debug:
        msg: "Using API server {{ kc_server.stdout }} and kubeconfig {{ kubeconfig_path }}"

  collections:
    - kubernetes.core

  module_defaults:
    kubernetes.core.helm:
      kubeconfig: "{{ kubeconfig_path }}"
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    NO_PROXY: "127.0.0.1,localhost,10.0.0.0/8,.svc,.cluster.local,{{ rke2_server_ip }}"
    no_proxy: "127.0.0.1,localhost,10.0.0.0/8,.svc,.cluster.local,{{ rke2_server_ip }}"

  roles:
    - { role: kube_labels,   tags: ["labels","ingress"] }
    - { role: cert_manager,  tags: ["cert","letsencrypt"] }   # ← すでに追加済みならそのまま
    - { role: ingress_nginx, tags: ["ingress"] }

  post_tasks:
    - name: Force strategy=Recreate on ingress-nginx-ops-controller (avoid pending on ports)
      kubernetes.core.k8s:
        state: patched
        kind: Deployment
        api_version: apps/v1
        name: ingress-nginx-ops-controller
        namespace: ingress-nginx-ops
        merge_type: merge 
        definition:
          spec:
            strategy:
              type: Recreate
              rollingUpdate: null
