---
- hosts: bastion
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml

  # kubeconfig を明示（他の playbook と同じ流儀）
  vars:
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') | default(playbook_dir | dirname ~ '/.kube/rke2.yaml', true) }}"

  module_defaults:
    kubernetes.core.helm:
      kubeconfig: "{{ kubeconfig_path }}"
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ kubeconfig_path }}"
    kubernetes.core.helm_repository:
      kubeconfig: "{{ kubeconfig_path }}"

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  roles:
    - { role: monitoring, tags: ["monitoring","prometheus","grafana"] }

