---
- name: Configure CoreDNS on RKE2 nodes with systemd-resolved
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  hosts:
    - masters
    - workers
  become: true
  tasks:

    - name: Gather service facts
      service_facts:

    - name: Backup existing resolved.conf
      copy:
        src: /etc/systemd/resolved.conf
        dest: /etc/systemd/resolved.conf.bak
        remote_src: yes
        force: no

    - name: Set DNS to CoreDNS in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNS='
        line: 'DNS=10.43.0.10'
        state: present

    - name: Set search domains in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?Domains='
        line: 'Domains=svc.cluster.local cluster.local'
        state: present

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
        enabled: true
      when: "'systemd-resolved.service' in ansible_facts.services"

    - name: Ensure /etc/resolv.conf is symlinked to systemd-resolved
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

