---
- name: Configure containerd with harbor.ip-163-220-178-113.compute.mdx1.jp:30643 as an insecure registry
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  hosts:
    - masters
    - workers
    - new_workers
  become: true
  tasks:

    - name: Remove legacy certs.d directory and hosts.toml for internal Harbor
      file:
        path: "/etc/containerd/certs.d/harbor.harbor.svc.cluster.local"
        state: absent

    - name: Check if harbor.harbor.svc.cluster.local:80 directory exists
      stat:
        path: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/harbor.harbor.svc.cluster.local:80"
      register: harbor_cert_dir_80

    - name: Force remove harbor.harbor.svc.cluster.local:80 directory using file module
      file:
        path: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/harbor.harbor.svc.cluster.local:80"
        state: absent
        force: yes

    - name: Remove old external Harbor registry certs.d directory
      file:
        path: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/harbor.ip-163-220-178-192.compute.mdx1.jp:30443"
        state: absent

    - name: Remove old Harbor registry certs.d directory with port 30580 if exists
      file:
        path: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/harbor.ip-163-220-178-113.compute.mdx1.jp:30580"
        state: absent

    - name: Create certs.d directory for new external Harbor registry
      file:
        path: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/10.14.22.78:30643"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy harbor.cert to containerd certs.d directory
      copy:
        src: files/harbor.crt
        dest: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/10.14.22.78:30643/ca.crt"
        owner: root
        group: root
        mode: '0644'

    - name: Create hosts.toml for new external Harbor registry
      copy:
        dest: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d/10.14.22.78:30643/hosts.toml"
        owner: root
        group: root
        mode: '0644'
        content: |
          server = "https://10.14.22.78:30643"

          [host."https://10.14.22.78:30643"]
            capabilities = ["pull", "resolve"]
            skip_verify = true

    - name: Ensure harbor hostname is resolvable via /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "10.14.22.78 harbor.ip-163-220-178-113.compute.mdx1.jp"
        state: present
        create: yes

    - name: Restart rke2-agent if service exists
      shell: |
        systemctl is-active --quiet rke2-agent && systemctl restart rke2-agent || echo "rke2-agent not running"

    - name: Restart rke2-server if service exists
      shell: |
        systemctl is-active --quiet rke2-server && systemctl restart rke2-server || echo "rke2-server not running"

