---
- name: Add cilium repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install/upgrade cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    create_namespace: false
    kubeconfig: "{{ kubeconfig_path }}"
    values_files:
      - roles/cilium/files/values-cilium.yaml
