---
- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install or upgrade Cilium using Helm CLI
  command: >
    helm upgrade --install cilium cilium/cilium
      --namespace kube-system
      --version 1.18.1
      --values {{ role_path }}/files/cilium-operator-fix.yaml
      --timeout 600s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Render cilium-config override ConfigMap
  ansible.builtin.template:
    src: "{{ role_path }}/templates/cilium-config.override.yaml.j2"
    dest: "/tmp/cilium-config.override.yaml"

- name: Apply cilium-config override
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    force: true
    src: "/tmp/cilium-config.override.yaml"

- name: Restart Cilium DaemonSet to reload config
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: patched
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: cilium
        namespace: kube-system
      spec:
        template:
          metadata:
            annotations:
              reload-at: "{{ lookup('pipe', 'date +%s') }}"

