controller:
  kind: Deployment
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
    externalTrafficPolicy: Local
  nodeSelector:
    ingress: "enabled"
  ingressClassResource:
    default: true
