---
- name: Install RKE2 server
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL={{ rke2_channel }} sh -
  args:
    creates: /usr/local/bin/rke2
  become: true

- name: Ensure RKE2 config dir exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"
  become: true

- name: Ensure RKE2 server data dir (token) exists
  file:
    path: /var/lib/rancher/rke2/server
    state: directory
    owner: root
    group: root
    mode: "0700"
    recurse: true
  become: true

# トークンの永続化と再利用
- name: Load existing token if present
  slurp:
    src: /var/lib/rancher/rke2/server/token
  register: existing_token
  ignore_errors: true
  become: true

- name: Set token from existing file or generate new
  set_fact:
    rke2_token: >-
      {{ (existing_token['content'] is defined and (existing_token['content'] | length | int > 0))
         | ternary(existing_token['content'] | b64decode | trim, lookup('password', '/dev/null', length=40, chars='hex')) }}

- name: Create token file
  copy:
    dest: /var/lib/rancher/rke2/server/token
    content: "{{ rke2_token }}\n"
    mode: "0600"
  become: true

# config.yaml の配布
- name: Place server config
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: rke2_config_file
  become: true

- name: Enable & start rke2-server
  systemd:
    name: rke2-server
    enabled: true
    state: started
  become: true


- name: Reset failed state for rke2-server
  command: systemctl reset-failed rke2-server
  become: true
  ignore_errors: true

- name: Wait for rke2-server to be active
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    timeout: 600
  become: true

- name: Restart rke2-server if config changed
  systemd:
    name: rke2-server
    state: restarted
  when: rke2_config_file is changed or (rke2_registries_file_pre is defined and rke2_registries_file_pre is changed)
  become: true

- name: Wait kubeconfig present
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    timeout: 600
  become: true

# RKE2起動 → kubeconfig 取得
- name: Fetch kubeconfig to controller (repo ./.kube)
  fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "{{ playbook_dir | dirname }}/.kube/rke2.yaml"
    flat: true
  become: false

