expose:
  type: nodePort
  tls:
    enabled: true
    secretName: harbor-tls      
    auto:
      commonName: harbor.ip-163-220-178-192.compute.mdx1.jp
  nodePort:
    ports:
      http:
        port: 80 
        nodePort: 30180
      https:
        port: 443
        nodePort: 30543
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"

externalURL: https://harbor.ip-163-220-178-192.compute.mdx1.jp:30543

harborAdminPassword: "ChangeMe#Harbor1"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 100Gi
      storageClass: local-path-wffc
    database:
      size: 10Gi
      storageClass: local-path-wffc
    trivy:
      size: 5Gi
      storageClass: local-path-wffc
    redis:
      size: 1Gi
      storageClass: local-path-wffc
    chartmuseum:
      size: 5Gi
      storageClass: local-path-wffc

