---
- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Install cert-manager (CRDs included)
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      installCRDs: true

- name: Render ClusterIssuer manifest
  template:
    src: clusterissuers.yaml.j2
    dest: /tmp/clusterissuers.yaml
  when: use_letsencrypt

- name: Apply ClusterIssuers
  kubernetes.core.k8s:
    state: present
    src: /tmp/clusterissuers.yaml
  when: use_letsencrypt

