---
- name: Add jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager (CRDs included)
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    values:
      installCRDs: true

- name: Render ClusterIssuer manifest
  template:
    src: clusterissuers.yaml.j2
    dest: /tmp/clusterissuers.yaml

- name: Apply ClusterIssuers
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/clusterissuers.yaml
